export default {
  hey: 'Hey,',
  login: 'Login Now',
  newString: 'If You are New / ',
  creteNow: 'Register Now',
  forgetPassword: 'Forgot Password / ',
  reset: 'Reset',
  fullName: 'Full Name',
  username: 'USERNAME',
  masterkey: 'Master Key',
  email: 'Email',
  password: 'Password',
  editProfile: 'Edit Profile',
  save: 'Save',
  masterKey: 'Master Key',
  import: 'Import',
  export: 'Export',
  logOut: 'Log Out',
  BASE_URL: 'https://securespot-api.herokuapp.com',
  BASE_URL2: 'http://securespot-lb-907628388.us-east-1.elb.amazonaws.com',
};
