export default {
  hey: 'Hey,',
  login: 'Login Now',
  newString: 'If You are New / ',
  creteNow: 'Register Now',
  forgetPassword: 'Forgot Password / ',
  reset: 'Reset',
  fullName: 'Full Name',
  username: 'Username',
  masterkey: 'Master Key',
  email: 'Email',
  password: 'Password',
  editProfile: 'Edit Profile',
  save: 'Save',
  masterKey: 'Master Key',
  import: 'Import',
  export: 'Export',
  logOut: 'Log Out',
};
